# Generated by Django 3.0.4 on 2020-03-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('user', '0003_auto_20200312_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='department.Department'),
        ),
    ]
